plugins {
    id 'java'
    id 'maven-publish'
}

group = ''  // Reemplaza con tu grupo
version = '1.0.0'  // Usa versión adecuada

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            
            // Configuración adicional opcional:
            artifact sourcesJar {
                classifier 'sources'
            }
            artifact javadocJar {
                classifier 'javadoc'
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/CUPUL-MIU-04/revanced-patches-kitsune"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

// Tareas opcionales para JARs de fuentes y javadoc
task sourcesJar(type: Jar) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

task javadocJar(type: Jar) {
    from javadoc
    classifier = 'javadoc'
}