name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev  # Manteniendo también la opción para dev si es necesario

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OTRO_TOKEN: ${{ secrets.OTRO_TOKEN }}  # Aquí se agrega el otro token
        run: ./gradlew build --no-daemon