name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        run: ./gradlew generatePatchesFiles clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Import GPG keys
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg_private_key_2: ${{ secrets.GPG_PRIVATE_KEY_2 }}
          passphrase_2: ${{ secrets.GPG_PASSPHRASE_2 }}
          fingerprint_2: ${{ secrets.GPG_FINGERPRINT_2 }}
          trust_level: 5

      - name: Configure Git signing
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global user.signingkey ${{ secrets.GPG_FINGERPRINT }}
          git config --global commit.gpgsign true
          git config --global gpg.program gpg

      - name: Release
        run: npm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ secrets.GPG_FINGERPRINT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Si necesitas publicar en npm