name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  release:
    name: Create Release
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: generatePatchesFiles clean

      - name: Generate patches files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew generatePatchesFiles clean --stacktrace --no-daemon

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global gpg.program gpg

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Solo necesario si publicas en npm
        run: npx semantic-release

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            patches.json
            README.md
          retention-days: 5